### ISSUE TITLE
Current TODO list

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/Marpa--R2#154]
- [x] Document $slr->ambiguous()
- [x] Document $slr->parse()
- [x] Revise Landing page
- [x] Revise Tutorial 2 page.
